application:
  host: 0.0.0.0
  port: 8000
  secure_cookies: true
  frontend_files_directory: "./dist"
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "andy@andybrauninger.com"
  timeout_milliseconds: 10000
